import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/banner'
import Card from '@/components/card';
import coffeeStores from '../data/coffee-stores.json';
import { GetStaticProps, InferGetStaticPropsType } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps: GetStaticProps<{ stores: Object[] }> = async (context) => {
  return {
    props: {
      stores: coffeeStores,
    }
  }
}

export default function Home({ stores }: InferGetStaticPropsType<typeof getStaticProps>) {

  const handleOnBannerBtnClick = () => {
    console.log('btn clicked!')
  };

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Banner
            btnText="View stores nearby"
            handleOnClick={handleOnBannerBtnClick}
          />
          <div className={styles.heroImage}>
            <Image src="/static/hero-image.png" width={700} height={400} alt="Coffee Connoisseur Hero Image" />
          </div>
        </div>

        {coffeeStores.length > 0 && 
        <>
          <h2 className={styles.heading2}>Toronto Stores</h2>
          <div className={styles.cardLayout}>
            {coffeeStores.map((store) => {
              return <Card
                key={store.id}
                name={store.name}
                imgUrl={store.imgUrl}
                href={`/coffee-store/${store.id}`}
              />
            })}
          </div>
        </>}
      </main>
    </>
  )
}
